name: 'GitHub Action FT Integration'
description: 'Sends CI/CD data from GitHub Action to OpenText SDP / SDM.'
inputs:
  octaneUrl:
    description: 'Url of OpenText SDP / SDM instance'
    required: true
  octaneSharedSpace:
    description: 'Shared Space ID'
    required: true
  octaneWorkspace:
    description: 'Workspace ID'
    required: true
  octaneClientId:
    description: "OpenText SDP / SDM API Access Client ID"
    required: true
  octaneClientSecret:
    description: 'OpenText SDP / SDM API Access Client Secret'
    required: true
  digitalLabUrl:
    description: 'OpenText Functional testing Lab Server URL, format: http(s)://{hostname-or-ip}[:{port}]'
    required: false
    default: ""
  digitalLabExecToken:
    description: 'OpenText Functional testing Lab Exec Token'
    required: false
    default: ""
  gitHubToken:
    description: 'GitHub PAT'
    required: true
  minSyncInterval:
    description: 'Minimum number of minutes to pass between 2 synchronizations'
    required: false
    default: "2"
  logLevel:
    description: 'Sets the log level (1-5): 1-trace, 2-debug, 3-info, 4-warn, 5-error'
    required: false
    default: "3"
runs:
  using: 'node20'
  main: 'dist/index.js'
